# Generated by Django 5.2.3 on 2025-06-14 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotiff',
            name='tiles_path',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='geotiff',
            name='source_file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['tif'])]),
        ),
    ]
