# Generated by Django 5.2.3 on 2025-06-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_geotiff_tiles_path_alter_geotiff_source_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geotiff',
            name='tiles_path',
        ),
    ]
